/*
  Copyright 2017, RackN
  DHCP Controller
*/
(function () {
  angular.module('app').controller('DHCPCtrl', [
    '$scope',
    function ($scope) {
      $scope.$emit('title', 'DHCP Subnets'); // shows up on the top toolbar

      $scope.expand = {};

      $scope.optionMap = {
        '0': 'Pad',
        '1': 'Subnet Mask',
        '2': 'Time Offset (deprecated)',
        '3': 'Router',
        '4': 'Time Server',
        '5': 'Name Server',
        '6': 'Domain Name Server',
        '7': 'Log Server',
        '8': 'Quote Server',
        '9': 'LPR Server',
        '10': 'Impress Server',
        '11': 'Resource Location Server',
        '12': 'Host Name',
        '13': 'Boot File Size',
        '14': 'Merit Dump File',
        '15': 'Domain Name',
        '16': 'Swap Server',
        '17': 'Root Path',
        '18': 'Extensions Path',
        '19': 'IP Forwarding enable/disable',
        '20': 'Non-local Source Routing enable/disable',
        '21': 'Policy Filter',
        '22': 'Maximum Datagram Reassembly Size',
        '23': 'Default IP Time-to-live',
        '24': 'Path MTU Aging Timeout',
        '25': 'Path MTU Plateau Table',
        '26': 'Interface MTU',
        '27': 'All Subnets are Local',
        '28': 'Broadcast Address',
        '29': 'Perform Mask Discovery',
        '30': 'Mask supplier',
        '31': 'Perform router discovery',
        '32': 'Router solicitation address',
        '33': 'Static routing table',
        '34': 'Trailer encapsulation',
        '35': 'ARP cache timeout',
        '36': 'Ethernet encapsulation',
        '37': 'Default TCP TTL',
        '38': 'TCP keepalive interval',
        '39': 'TCP keepalive garbage',
        '40': 'Network Information Service Domain',
        '41': 'Network Information Servers',
        '42': 'NTP servers',
        '43': 'Vendor specific information',
        '44': 'NetBIOS over TCP/IP name server',
        '45': 'NetBIOS over TCP/IP Datagram Distribution Server',
        '46': 'NetBIOS over TCP/IP Node Type',
        '47': 'NetBIOS over TCP/IP Scope',
        '48': 'X Window System Font Server',
        '49': 'X Window System Display Manager',
        '50': 'Requested IP Address',
        '51': 'IP address lease time',
        '52': 'Option overload',
        '53': 'DHCP message type',
        '54': 'Server identifier',
        '55': 'Parameter request list',
        '56': 'Message',
        '57': 'Maximum DHCP message size',
        '58': 'Renew time value',
        '59': 'Rebinding time value',
        '60': 'Class-identifier',
        '61': 'Client-identifier',
        '62': 'to 255  NetWare/IP Domain Name',
        '63': 'NetWare/IP information',
        '64': 'Network Information Service+ Domain',
        '65': 'Network Information Service+ Servers',
        '66': 'TFTP server name',
        '67': 'Bootfile name',
        '68': 'Mobile IP Home Agent',
        '69': 'Simple Mail Transport Protocol Server',
        '70': 'Post Office Protocol Server',
        '71': 'Network News Transport Protocol Server',
        '72': 'Default World Wide Web Server',
        '73': 'Default Finger Server',
        '74': 'Default Internet Relay Chat Server',
        '75': 'StreetTalk Server',
        '76': 'StreetTalk Directory Assistance Server',
        '77': 'User Class Information',
        '78': 'SLP Directory Agent',
        '80': 'Rapid Commit',
        '81': 'FQDN, Fully Qualified Domain Name',
        '82': 'Relay Agent Information',
        '83': 'Internet Storage Name Service',
        '85': 'NDS servers',
        '86': 'NDS tree name',
        '87': 'NDS context',
        '88': 'BCMCS Controller Domain Name list',
        '89': 'BCMCS Controller IPv4 address list',
        '90': 'Authentication',
        '91': 'client-last-transaction-time',
        '92': 'associated-ip',
        '93': 'Client System Architecture Type',
        '94': 'Client Network Interface Identifier',
        '95': 'LDAP, Lightweight Directory Access Protocol',
        '97': 'Client Machine Identifier',
        '98': 'Open Group\'s User Authentication',
        '99': 'GEOCONF_CIVIC',
        '100': 'IEEE 1003.1 TZ String',
        '101': 'Reference to the TZ Database',
        '112': 'NetInfo Parent Server Address',
        '113': 'NetInfo Parent Server Tag',
        '114': 'URL',
        '116': 'Auto-Configure',
        '117': 'Name Service Search',
        '118': 'Subnet Selection',
        '119': 'DNS domain search list',
        '120': 'SIP Servers DHCP Option',
        '121': 'Classless Static Route Option',
        '122': 'CCC, CableLabs Client Configuration',
        '123': 'GeoConf',
        '124': 'Vendor-Identifying Vendor Class',
        '125': 'Vendor-Identifying Vendor-Specific',
        '128': 'TFTP Server IP address',
        '129': 'Call Server IP address',
        '130': 'Discrimination string',
        '131': 'Remote statistics server IP address',
        '132': '802.1P VLAN ID',
        '133': '802.1Q L2 Priority',
        '134': 'Diffserv Code Point',
        '135': 'HTTP Proxy for phone-specific applications',
        '136': 'PANA Authentication Agent',
        '137': 'LoST Server',
        '138': 'CAPWAP Access Controller addresses',
        '139': 'OPTION-IPv4_Address-MoS',
        '140': 'OPTION-IPv4_FQDN-MoS',
        '141': 'SIP UA Configuration Service Domains',
        '142': 'OPTION-IPv4_Address-ANDSF',
        '143': 'OPTION-IPv6_Address-ANDSF',
        '150': 'TFTP server address / Etherboot GRUB configuration path name',
        '151': 'status-code',
        '152': 'base-time',
        '153': 'start-time-of-state',
        '154': 'query-start-time',
        '155': 'query-end-time',
        '156': 'dhcp-state',
        '157': 'data-source',
        '175': 'Etherboot',
        '176': 'IP Telephone',
        '177': 'Etherboot. PacketCable and CableHome',
        '208': 'pxelinux.magic (string) = F1:00:74:7E (241.0.116.126)',
        '209': 'pxelinux.configfile (text)',
        '210': 'pxelinux.pathprefix (text)',
        '211': 'pxelinux.reboottime (unsigned integer 32 bits)',
        '212': 'OPTION_6RD',
        '213': 'OPTION_V4_ACCESS_DOMAIN',
        '220': 'Subnet Allocation',
        '221': 'Virtual Subnet Selection',
        '254': 'Private use',
        '255': 'End.',
      }
    }
  ]);
})();
